#!/usr/bin/env bash

# =========================================================================

shell_runner() {
	cat - <<-SCRIPT
#!/usr/bin/env bash
PERL5LIB="\$( dirname "\$0" )/../home/.perl5/lib"
perl -I "\$PERL5LIB" -x -S "\$PERL5LIB/../bin/\$( basename "\$0" )$1" "\$@"
SCRIPT
}

batch_runner() {
	cat - <<-SCRIPT | unix2dos
@echo off
set PERL5LIB="%~dp0..\home\.perl5\lib"
perl -I "%PERL5LIB%" -x -S "%PERL5LIB%\..\bin\%~n0$1" %*
SCRIPT
}

# =========================================================================

DESTDIR="${1:-$HOME/bin}"

[ -d "$DESTDIR" ] || {
	echo "Not a directory: $DESTDIR"
	exit 1
}

cat - <<BANNER
Make runners for local Perl utilites
Destination: $DESTDIR"
BANNER

grep -c '^#!.*perl' "$( dirname "$0" )/bin"/* \
| while IFS=":" read f n
do
	if [ "$n" = "0" ]
	then
		echo "  Copying: $f"
		cp "$f" "$DESTDIR"
		continue
	fi

	g="$( basename "$f" .pl )"
	x=""
	[ "$g" = "$( basename "$f" )" ] || x=".pl"

	echo "  Perl script: $f"

	shell_runner "$x" > "$DESTDIR/$g"
	batch_runner "$x" > "$DESTDIR/$g.bat"
done

# =========================================================================

# EOF
