#! ~/.bash/aliases

# =========================================================================

# Aliases
#
# Some people use a different file for aliases
# if [ -f "${HOME}/.bash_aliases" ]; then
#   source "${HOME}/.bash_aliases"
# fi
#
# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
# alias df='df -h'
# alias du='du -h'
#
# Misc :)
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort

# Some versions do not support colorizing
if grep --color -V >/dev/null 2>&1
then
	alias grep='grep --color'               # show differences in colour
	alias egrep='egrep --color=auto'        # show differences in colour
	alias fgrep='fgrep --color=auto'        # show differences in colour
fi

# alias agrep='grep -a'

# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
alias ls='ls --color=tty'
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
alias ll='ls -l'                                # long list
alias la='ls -A'                                # all but . and ..
alias l='ls -CF'                                #

# =========================================================================

# The following section provides 4 different implementations to display
# file contents in ascii and hexadecimal. In fact, it's quite redundant
# because the most of these tools are available in Linux and Cygwin-like
# environments.
if which od > /dev/null 2>&1
then
	# http://www.pixelbeat.org/settings/.bashrc
	alias hd='od -Ax -tx1z -v'
elif which hexdump > /dev/null 2>&1
then
	alias hd='hexdump -C'
elif which xxd > /dev/null 2>&1
then
	alias hd='xxd -g1'
else
	# perl implementing xdd -g1
	alias hd=xxd_g1
	xxd_g1() {
		perl -000 -e '
		for ( <> =~ /.{1,16}/gs ) {
			@d = unpack("H32") =~ /../g;
			s/[^[:print:]]/./g;
			printf "%08x: %-48s %s\n", $o, "@d", $_;
			$o += 16;
		}
		'
	}
fi

# =========================================================================

if which colordiff > /dev/null 2>&1
then
	alias diff=colordiff
fi

# =========================================================================

# Windows only (Cygwin or MSys)
case "$( uname | tr [:upper:] [:lower:] )" in
cygwin* | msys* | mingw* )
	alias ps='ps -W'
	;;
esac

# =========================================================================

# https://github.com/rprichard/winpty
#
# Creating alias to winpty, the package providing interface between Window 
# console and Unix-like pty used in cygwin, msysgit and others.
if which winpty > /dev/null 2>&1
then
	alias winpty="$( which winpty )"
else
	case "$( uname | tr [:upper:] [:lower:] )" in
	cygwin* )
		# Presume that winpty is under CYGROOT/../winpty
		WINPTY="$( cygpath "$( cygpath -m / )/../winpty" )"
		;;
	msys* | mingw* | windows* )
		# Presume that winpty is under MSYSROOT/../winpty
		WINPTY="$( cd "$( cd / ; pwd -W )/../winpty" ; pwd )"
		;;
	esac

	if [ -n "$WINPTY" -a -x "$WINPTY/$OSTYPE/console" ]
	then
		alias winpty="$WINPTY/$OSTYPE/console"
	elif [ -n "$WINPTY" -a -x "$WINPTY/$OSTYPE/bin/winpty" ]
	then
		alias winpty="$WINPTY/$OSTYPE/bin/winpty"
	fi

	unset WINPTY
fi

# =========================================================================

# Ant related aliases

# Few ways to customize Ant:
# 1. Create alias ant with the particular command line options.
# 2. Export ANT_ARGS environment variable with the command line options.
# 3. Create ${HOME}/.ant.properties with prefedined properties.
#    This file allows to override some properties without editing 
#    Build.xml and without typing -D on each invocation. 
#    This way, build.xml should be able to read properties from this file.
# 4. Any combination of all the stuff above.
# alias ant='ant -find build.xml -emacs -Dium.install.dir=/opt/SIU'

# =========================================================================

# Git aliases
if which git >/dev/null 2>&1
then
	# http://gitimmersion.com/lab_11.html
	alias gs='git status'
	# alias ga='git add'
	alias gb='git branch'
	# http://stackoverflow.com/a/11585743/3627676
	# alias gbn='git name-rev --name-only HEAD'
	# alias gc='git commit'
	alias gd='git diff'
	alias go='git checkout'
	alias gl='git log'
	alias gll='git log --name-status'
	alias gli='LESS="-RS" git log --color --graph --oneline'
	alias gla='LESS="-RS" git log --color --graph --oneline --decorate --all'
	# alias gk='gitk --all&'
	# alias gx='gitx --all'
	# alias got='git'
	# alias get='git'

	alias ggu='git config --local remote.origin.url'
	alias ggn='git config --local remote.origin.url | sed "s|.*/||;s|\.[^.]*$||"'
	alias ggr='git rev-parse --show-toplevel'
	alias ggg='git rev-parse --git-dir'
	alias ggb='git rev-parse --abbrev-ref HEAD'

	# /cygdrive if cygwin default settings or emty string otherwise
	drive_prefix="$( mount -p 2>/dev/null | sed -n '2s/[ ]*[^ ]*[ ]*[^ ]*$//p' | grep -vx '/' )"

	# cd to home dir for personal gits
	alias cdgp='cd "$( git-bunch priv )" && ls'

	# cd to home dir for gits used at work
	alias cdgw='cd "$( git-bunch work )" && ls'

	unset drive_prefix

	# Do cd to the git root dir (if it's possible
	alias cdggr='cd "$( ggr )"'
fi

# =========================================================================

if which perl >/dev/null 2>&1
then
	# `whichpm` reports the filesystem path of Perl modules by module 
	# (package) name, similar to what the Unix `which` utility does 
	# for binaries.
	# See also:
	# https://github.com/mklement0/whichpm
	alias whichpm='perldoc -lm'
fi

# =========================================================================

# EOF
