#!/bin/bash

# =========================================================================

now() {
	local args="$@"
	date "+%F %T" ${args:+ -d "$args"}
}

today() {
	local args="$@"
	date "+%F" ${args:+ -d "$args"}
}

tomorrow() {
	today "+1 day $@"
}

yesterday() {
	today "-1 day $@"
}

# =========================================================================

# EOF
