#! ~/.bash/functions-jump

# =========================================================================

# Jump around anywhere
# It's developed simple as much as possible:
# - Keep the list of directories and aliases in the "~/.jconf" TSV-file
# - Allow to jump to the directories fastly by aliases
# - Listing of directories by its aliases
# - Display listing of available directories and aliases
#
# Other projects implementing the same functionalities:
# https://github.com/rupa/z
# https://github.com/mfaerevaag/wd
j() {
	if [ $# -eq 0 ]
	then
		cat - <<HELP
Jump around anywhere
  j    ALIAS [SUBDIR] Jump to the directory by its alias
  j -l ALIAS [SUBDIR] List the directory content
  j -a ALIAS          Create the alias for the current directory
  j -d ALIAS          Delete the alias
  j -A                Display all directories and their aliases
HELP
		return
	fi

	local CONF=~/.jconf

	# Estimate the prefix for Cygwin, Msys2 and so on.
	# It differs for different systems:
	# - "/cygdrive/" for Cygwin (NB: the single trailing slash)
	# - "/" for Msys2
	# - empty string for real Unix environments
	local prefix="$(
		cd -P /proc/cygdrive 2>/dev/null || exit 0
		echo "${PWD%%/}/"
	)"

	local jcmd="cd"

	OPTIND=1

	local opt
	while getopts ":la:d:A" opt
	do
		case "$opt" in
		l )
			jcmd="ls"
			break
			;;
		a )
			# Prevent adding the same alias
			if [ -f "$CONF" ] && grep -Pq "^$OPTARG\t" "$CONF"
			then
				echo "Alias already exists: $OPTARG" >&2
				return 255
			fi

			printf '%s\t%s\n' "$OPTARG" "${PWD#$prefix}" >>"$CONF"
			return $?
			;;
		d )
			# No file, nothing to delete -- no error
			[ -f "$CONF" ] || return 0

			sed -i "/^$OPTARG\t/d" "$CONF"
			return $?
			;;
		A )
			# No file, nothing to display -- error
			[ -f "$CONF" ] || {
				echo "File not exist: ~/.jconf" >&2
				return 255
			}

			sort "$CONF"
			return $?
			;;
		: )
			echo "Alias required" >&2
			return 255
			;;
		\? )
			echo "Bad option: $OPTARG"
			return 255
			;;
		esac
	done

	shift $(( OPTIND - 1 ))

	if [ -z "$1" ]
	then
		echo "Alias not specified" >&2
		return $?
	fi

	local -a jdir
	mapfile -t jdir < <( sed -n "s/^$1\t*//p" "$CONF" )

	case "${#jdir[@]}" in
	0 )
		echo "Alias not found: $1" >&2
		return 255
		;;
	1 )
		# FIXME!!! Sometimes it fails -- for example:
		# 1. run under Msys2
		#    cd /tmp ; j -a zzz
		# 2. run under Cygwin
		#    j zzz
		# It happens because Msys2 creates "zzz {TAB} tmp"
		# And further Cygwin tries to "cd /cygdrive/tmp"
		[ "${jdir[0]:0:1}" = "/" ] && prefix=""
		# cd or ls
		$jcmd "$prefix${jdir[0]}/$2"
		;;
	* )
		echo "More than one alias found: $1" >&2
		return 255
		;;
	esac
}

# =========================================================================

# EOF
