#! ~/.bash/settings-git

# =========================================================================

# Git settings
declare -F | grep -q _git && return

for f in \
	"$HOME/.git-completion.bash" \
	"/etc/git-completion.bash" \
	"/mingw64/share/git/completion/git-completion.bash" \
	"/mingw32/share/git/completion/git-completion.bash" \

do
	if [ -f "$f" ]
	then
		. "$f"
		break
	fi
done

for f in \
	"$HOME/.git-prompt.sh" \
	"/etc/git-prompt.sh" \
	"/mingw64/share/git/completion/git-prompt.sh" \
	"/mingw32/share/git/completion/git-prompt.sh" \

do
	if [ -f "$f" ]
	then
		. "$f"
		break
	fi
done

unset f

# =========================================================================

# EOF
